### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by dnicolson**
## :recycle: Current situation

Some optional chaining operators were introduced after others being removed in https://github.com/OpenWonderLabs/node-switchbot/pull/232.

## :bulb: Proposed solution

Remove them and fix new warnings.

@brozef I assume you removed the optional chaining operators for Node.js 12 compatibility but are passing the `noble` instance, as the [dynamic import](https://github.com/OpenWonderLabs/node-switchbot/blob/c0a3668/src/switchbot.ts#L65) is only supported in Node.js 14.

### CODE REVIEW

**Comment by donavanbecker** [comment]
I will wait a few days for @brozef to respond. If not we will merge.

**Comment by donavanbecker** [comment]
I am merging, if we need to revert we can.

**Comment by donavanbecker** [comment]
Build failed @dnicolson

**Comment by dnicolson** [comment]
Those are just TypeScript warnings, I will override the type definition until Noble 1.9.2-25 is released.

**Comment by brozef** [comment]
looks good thanks @dnicolson

**Pull request merged**
