### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by donavanbecker**
### What's Changed
- Rewrite into Typescript and Convert CommonJS to ES Module
- Fix Linting, Thanks [@dnicolson](https://github.com/dnicolson) [#216](https://github.com/OpenWonderLabs/node-switchbot/pull/216)
- Code Cleaup, Thanks [@dnicolson](https://github.com/dnicolson) [#217](https://github.com/OpenWonderLabs/node-switchbot/pull/217)
- Housekeeping and update dependencies

**Full Changelog**: https://github.com/OpenWonderLabs/node-switchbot/compare/v1.10.0...v2.0.0

### CODE REVIEW

**Comment by donavanbecker** [comment]
@dnicolson, do you have any thoughts on this?

**Comment by dnicolson** [comment]
Nothing comes to mind.

When including it in `homebridge-switchbot` I wouldn't release it as part of a patch release. I see you ultimately reverted part of the changes, the `node-switchbot` import is broken though, unfortunately.

**Comment by donavanbecker** [comment]
Dang, well hopefully we can get this resolved. I will open another beta with a minor change version. To release node-SwitchBot with that.

**Comment by dnicolson** [comment]
@donavanbecker, I'm not sure how you want to solve this, but the problem with this release is an async issue in the constructor. The scanning code gets called before `noble` has been imported.

You can easily test before making a release, just by running something like `test.mjs` in the project directory after building:

```
import { SwitchBot } from './dist/index.js';

const switchbot = new SwitchBot();

(async () => {
  await switchbot.startScan({ id: 'XX:XX:XX:XX:XX:XX' });
  switchbot.onadvertisement = (ad) => {
    console.log(JSON.stringify(ad, null, '  '));
  };
})();

```

**Comment by donavanbecker** [comment]
> ```
> import { SwitchBot } from './dist/index.js';
> 
> const switchbot = new SwitchBot();
> 
> (async () => {
>   await switchbot.startScan({ id: 'XX:XX:XX:XX:XX:XX' });
>   switchbot.onadvertisement = (ad) => {
>     console.log(JSON.stringify(ad, null, '  '));
>   };
> })();
> ```

would you want to add something like this to the repo that can be ran each time before publishing?

**Comment by dnicolson** [comment]
Maybe, the effectiveness would need to be evaluated though.

**Pull request merged**
