### PR TITLE
Modify Curtain's action command to support group and running mode

### PR DESCRIPTION
**Pull request by SwitchBot-Wonderlabs**
Hi，Futomi，this is an update of  the Curtain.

### CODE REVIEW

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, Futomi, have you considered transferring this repository to switchbot for maintenance?

**Comment by futomi** [comment]
Thank you for the PR!

> Hi, Futomi, have you considered transferring this repository to switchbot for maintenance?

Do you mean transferring the ownership of this repository from me to you?
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

**Comment by SwitchBot-Wonderlabs** [comment]
Yes, we want to maintain related repositories when we have enough energy, so ask your opinion first.
The details have not yet been determined, but it should be to move the GitHub repository and NPM packages to the SwitchBot organization.

**Comment by futomi** [comment]
I agree with you. Would you do me a favor? Can you keep the software license MIT or equivalent?

**Comment by SwitchBot-Wonderlabs** [comment]
> I agree with you. Would you do me a favor? Can you keep the software license MIT or equivalent?

We will keep the MIT license.
When we are ready, I will trouble you to transfer the repository.

**Comment by futomi** [comment]
When you are ready, let me know. I'll transfer the ownerships of GitHub and npm. Thank you.

**Pull request merged**
