### PR TITLE
Fixed 'TypeError: Assignment to constant variable'.

### PR DESCRIPTION
**Pull request by banboobee**
Fixed run-time error 'TypeError: Assignment to constant variable' for meter devices. #184 introduced this bug.

### CODE REVIEW

**Comment by donavanbecker** [comment]
@dnicolson Can you review?

**Comment by donavanbecker** [comment]
@banboobee Can you rebranch to beta-1.8.2 branch?

**Comment by dnicolson** [comment]
Looks good to me.

**Comment by dnicolson** [comment]
@banboobee thanks for the original fix, I've included it with other similar issues in #196.

@donavanbecker can you please look at the remaining lint issues in #195? There should be only 5 linting issues left.

**Comment by banboobee** [comment]
Re-branched.

I didn't know the beta-branch, but now find that it intends to identical with this PR. omg, I wasted a lot of time.

 This PR also added the support for meter-plus device.

**Comment by dnicolson** [comment]
@banboobee I think you'll want to do a rebase over the `beta-1.8.2` branch first to see the changes for the other device. I'd be happy to help as it can get confusing with different branches.

There is still the problematic second instance here:
https://github.com/OpenWonderLabs/node-switchbot/blob/2e7c86e/lib/switchbot-advertising.js#L598-L599

I've included it with other fixes here though:
https://github.com/OpenWonderLabs/node-switchbot/pull/196/files#diff-1b0556c723f9c442161c41856a41ad860ec36d7262199f3b12d1a63c877d7611R600

**Review by donavanbecker — APPROVED** [review]

**Comment by dnicolson** [comment]
@donavanbecker this merge (`git diff cf91f59..d9e963f`) didn't actually change anything as it was covered in `git diff 2e7c86e..cf91f59` (#196).

@banboobee could you maybe create a new PR with the meter-plus changes?

**Comment by donavanbecker** [comment]
@banboobee, I am about to release the next version. Any chance you can create a new PR so that I can merge it into this version?

**Comment by banboobee** [comment]
What do you mean? New PR for meter-plus? It is included in this PR.

**Comment by donavanbecker** [comment]
@banboobee So does the latest version resolve your issues?

**Comment by banboobee** [comment]
Yes.

With v1.8.1, meter and meter-plus are stopped working for these three months.

@gravity-addiction fixed for meter in #191, and #194 (this PR) added the fix for meter-plus.

So, v1.8.2 fixed both issues. meter and meter-plus are working again, I believe.

**Pull request merged**
